services:
  - type: web
    name: my-laravel-portfolio
    env: docker
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 
10000

